### ISSUE TITLE
Content aware cropping mode

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#62]
It may be nice to have a look at https://github.com/jwagner/smartcrop.js and determine if that is a good candidate for a new cropping mode (in addition to the `aoi_auto` crop mode).

**Comment by trendfischer** [comment]
I just stumbled over the lib and wanted to propose it here, too. Seems to be a good solution for the problem.

Although it requires a canvas object. The CLI https://github.com/jwagner/smartcrop-cli uses node-canvas, which depends on cairo and require a C++ compile environment for installation, see https://github.com/Automattic/node-canvas

Thus in mind, the cropping mode should be optional, since a compile environment on a server is some sort of bad practice.
